import { useEffect, useRef } from "react";
import Head from "next/head";
import Mysection from "../components/Mysection";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();
  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container ${styles.container}`}>
        <div ref={section1}>
          <Mysection
            image={`/images/austin-neill-Be7DMcK7k3o-unsplash.jpg`}
            headline={`Lorem Ipsum Dolor Sit Amet`}
            goToSectionRef={section2}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section2}>
          <Mysection
            image={`/images/chris-chan-wA-dbT3FJnE-unsplash.jpg`}
            headline={`Lorem Ipsum Dolor Sit Amet`}
            goToSectionRef={section3}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section3}>
          <Mysection
            image={`/images/michael-olsen--djS1aPrSr4-unsplash.jpg`}
            headline={`Lorem Ipsum Dolor Sit Amet`}
            goToSectionRef={section1}
            scrollTo={scrollTo}
            showArrow={false}
          />
        </div>
      </div>
    </div>
  );
}
